[package]
name = "dice-roller"
description = "Roll dice for rollplaying games from the command line!"
version = "1.0.0"
authors = ["Laura Demkowicz-Duffy <edward70891@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
structopt = "0.3.12"
