[package]
name = "dndice"
description = "Roll dice for roleplaying games from the command line"
version = "1.3.0"
authors = ["Laura Demkowicz-Duffy <edward70891@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.7.3", features = ["small_rng"] }
structopt = "0.3.12"
